/** Jeu de démo — même forme qu’un futur export JSON Go. */
export const CABINET_DEMO = {
  jeuneInstalleZip: true,
  medecinPlus67Ans: false,
}

export const MOCK_PATIENTS = [
  {
    id: 'P-001',
    prenom: 'Marie',
    nom: 'MARTIN',
    age: 78,
    sexe: 'F',
    ald: true,
    c2s: true,
    diabetique: false,
    derniereVisite: '2022-04-10',
    indicateursFaits: { mammographie: true },
  },
  {
    id: 'P-002',
    prenom: 'Jean',
    nom: 'DUPONT',
    age: 66,
    sexe: 'M',
    ald: true,
    c2s: false,
    diabetique: true,
    derniereVisite: '2025-01-15',
    indicateursFaits: { grippe: true, hba1c: true },
  },
  {
    id: 'P-003',
    prenom: 'Léa',
    nom: 'BERNARD',
    age: 42,
    sexe: 'F',
    ald: false,
    c2s: true,
    diabetique: false,
    derniereVisite: '2025-11-01',
    indicateursFaits: {},
  },
  {
    id: 'P-004',
    prenom: 'Ahmed',
    nom: 'KADDOUR',
    age: 58,
    sexe: 'M',
    ald: true,
    c2s: false,
    diabetique: false,
    derniereVisite: '2023-08-20',
    indicateursFaits: { covid: true },
  },
  {
    id: 'P-005',
    prenom: 'Chloé',
    nom: 'PETIT',
    age: 1,
    sexe: 'F',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2025-12-01',
    indicateursFaits: { m9: true },
  },
  {
    id: 'P-006',
    prenom: 'Hugo',
    nom: 'GARCIA',
    age: 16,
    sexe: 'M',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2025-06-10',
    indicateursFaits: {},
  },
  {
    id: 'P-007',
    prenom: 'Sophie',
    nom: 'LAURENT',
    age: 62,
    sexe: 'F',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2024-10-05',
    indicateursFaits: { colorectal: true, mammographie: true },
  },
]
