/** Jeu de démo — même forme qu’un futur export JSON Go. */

/** Si renseigné (ex. URL LGC), le bouton Dossier ouvre un onglet ; sinon copie de l’id. */
export const DOSSIER_PATIENT_BASE_URL = ''

/** Bandeau ordre du jour / période — à remplacer par API agenda. */
export const AGENDA_DEMO = {
  rendezVousAujourdhui: 12,
  periodeLibelle: 'Année civile 2026 (indicatif)',
}

export const CABINET_DEMO = {
  jeuneInstalleZip: true,
  medecinPlus67Ans: false,
}

export const MOCK_PATIENTS = [
  {
    id: 'P-001',
    prenom: 'Marie',
    nom: 'MARTIN',
    age: 78,
    sexe: 'F',
    ald: true,
    c2s: true,
    diabetique: false,
    mcva: false,
    derniereVisite: '2022-04-10',
    indicateursFaits: { grippe: true, covid: true, pneumocoque: true },
    syntheseMedicale:
      'HTA longue évolution, risque cardiovasculaire modéré. Dernière visite ancienne : risque de perte de forfait.',
    pointsAttention: 'Visite à programmer en priorité ; hors tranches dépistage sein/colorectal (âge).',
  },
  {
    id: 'P-002',
    prenom: 'Jean',
    nom: 'DUPONT',
    age: 66,
    sexe: 'M',
    ald: true,
    c2s: false,
    diabetique: true,
    risquePneumocoqueSevere: true,
    derniereVisite: '2025-01-15',
    indicateursFaits: { grippe: true, hba1c: true, pneumocoque: true },
    syntheseMedicale: 'Diabète type 2 équilibré ; suivi HbA1c régulier.',
    pointsAttention: 'Vaccination COVID à compléter selon campagne.',
  },
  {
    id: 'P-003',
    prenom: 'Léa',
    nom: 'BERNARD',
    age: 42,
    sexe: 'F',
    ald: false,
    c2s: true,
    diabetique: false,
    mcva: true,
    derniereVisite: '2025-11-01',
    indicateursFaits: { colUterus: true },
    syntheseMedicale: 'Patient en précarité (C2S) ; MCVA documentée.',
    pointsAttention: 'Glycémie à jeun et MRC selon critères FMT.',
  },
  {
    id: 'P-004',
    prenom: 'Ahmed',
    nom: 'KADDOUR',
    age: 58,
    sexe: 'M',
    ald: true,
    c2s: false,
    diabetique: false,
    risquePneumocoqueSevere: true,
    derniereVisite: '2023-08-20',
    indicateursFaits: { covid: true, colorectal: true },
    syntheseMedicale: 'ALD stable ; dernière consultation > 18 mois.',
    pointsAttention: 'Grippe et pneumocoque ; relance prévention.',
  },
  {
    id: 'P-005',
    prenom: 'Chloé',
    nom: 'PETIT',
    age: 1,
    ageMois: 14,
    sexe: 'F',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2025-12-01',
    indicateursFaits: { meningocoqueC: true },
    syntheseMedicale: 'Nourrisson ; calendrier vaccinal et consultations M9.',
    pointsAttention: 'M9 entre 8e et 10e mois ; ROR à anticiper.',
  },
  {
    id: 'P-006',
    prenom: 'Hugo',
    nom: 'GARCIA',
    age: 14,
    sexe: 'F',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2025-06-10',
    indicateursFaits: { buccoDentaire: true },
    syntheseMedicale: 'Adolescente ; HPV et suivi bucco-dentaire.',
    pointsAttention: 'Deuxième dose HPV si applicable.',
  },
  {
    id: 'P-007',
    prenom: 'Sophie',
    nom: 'LAURENT',
    age: 62,
    sexe: 'F',
    ald: false,
    c2s: false,
    diabetique: false,
    derniereVisite: '2024-10-05',
    indicateursFaits: { colorectal: true, sein: true, colUterus: true },
    syntheseMedicale: 'Dépistages organisés à jour sur les tranches éligibles.',
    pointsAttention: 'Contrôle visite FMT avant 24 mois.',
  },
]
